AWSTemplateFormatVersion: 2010-09-09
#  _____
# |_   _|
#   | |    __ _ __      __
#   | |   / _` |\ \ /\ / /
#  _| |_ | (_| | \ V  V /
# |_____| \__, |  \_/\_/
#          __/ |
#         |___/
Resources:
  InternetGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: cfn-training-igw
Outputs:
  IgwOut:
    Value: !Ref InternetGW
    Export:
      Name: CreateIgw
